### PR TITLE
Added elevations file with all elevations according to the guideline

### PR DESCRIPTION
**Pull request by vanniktech**
Could be helpful too.

### CODE REVIEW

**Comment by mcginty** [comment]
Thanks for the PR @vanniktech! Sorry I was traveling and missed this earlier. Will take a look.

**Comment by vanniktech** [comment]
Alright thank you very much for the heads up.

**Comment by vanniktech** [comment]
@mcginty what's the status on this one?

**Comment by vanniktech** [comment]
Closing since this PR is super old

**Comment by mcginty** [comment]
while incredibly delayed, i integrated the elevations in v1.1.0. thanks and sorry it got ignored!

**Pull request closed without merging**
